TB_path: 'runs/exp1'

num_epochs: 1
loss_function: CrossEntropyLoss
optimizer:
  name: Adam
  lr: 0.001

batch_size: 1
num_workers: -1

device: cpu #cuda:0 # cpu or cuda:0 for single GPU or [0,1] for multiple GPU

# TB writer stuff
log_training_loss: True
log_validation_loss: True


# DDPM Stuff
distributed: False
MASTER_ADDR: localhost
MASTER_PORT: 11255
rank: 1
world_size: 1

model:
  [
    [-1, 1, TB_object, ['add_image', 'input_image', None]],
    [-1, 1, Conv2d, [3, 64, 3, 1, 1]], # Line 0
    [-1, 1, TB_object, ['add_image', 'conv2d_output', None], [TB_object, 'add_image', 'input_image', None]],
    [-1, 1, MaxPool2d, [2, 2]], # Line 1
    [-1, 1, Flatten, [1]],
    [-1, 1, Linear, [1048576, 1]],
    
  ]